version: "3.8"

services:
    nats-server:
        image: nats:latest
        ports:
            - "4222:4222"
            - "8222:8222"
        networks:
            - nats-network

    auth-service-db:
        image: mongo:latest
        container_name: auth-service-db
        ports:
            - "27018:27017" # Maps external port 27018 to internal MongoDB port 27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - auth-service-db-data:/data/db
        networks:
            - auth-service-network

    auth-service:
        build: ./auth-service
        ports:
            - "3000:3000"
        environment:
            - NATS_URL=nats-server:4222
            - MONGO_URL=mongodb://root:example@auth-service-db:27017
            - JWT_SECRET=secret
        depends_on:
            - nats-server
            - auth-service-db
        networks:
            - auth-service-network
            - nats-network
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost:3000/"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5
    
    event-service-db:
        image: mongo:latest
        container_name: event-service-db
        ports:
            - "27019:27017" # Maps external port 27018 to internal MongoDB port 27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - event-service-db-data:/data/db
        networks:
            - event-service-network

    event-service:
        build: ./event-service
        ports:
            - "3001:3000"
        environment:
            - NATS_URL=nats-server:4222
            - MONGO_URL=mongodb://root:example@event-service-db:27017
            - JWT_SECRET=secret
        depends_on:
            - nats-server
            - event-service-db
        networks:
            - event-service-network
            - nats-network
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost:3000/"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5

volumes:
    auth-service-db-data:
    event-service-db-data:

networks:
    auth-service-network:
        driver: bridge
    event-service-network:
        driver: bridge
    nats-network:
        driver: bridge